### PR TITLE
Add elm-pages based generator

### PR DESCRIPTION
**Pull request by miniBill**
I wanted to update the data but failed to run the haskell code (there is some issue with NixOS and cabal/stack apparently) so I just... rewrote it in ~Rust~ Elm, using the new `elm-pages script` feature.

This is a draft because:
1. I don't know if you think this is a good idea
2. This PR is missing two other commits (removing the Haskell code and actually running the codegen to update country names)

### CODE REVIEW

**Comment by miniBill** [comment]
One option would be to switch to `elm-codegen` for generating the files. My current approach is oriented towards minimizing the diff

**Comment by rl-king** [comment]
Cool! I didn't know this existed. Would it help if I removed the stack dependency? That's something I would do anyway if I'd touch this repo again. I've been moving to just Cabal since Stack support on m1 was horrible. And it's actually all a bit nicer with Cabal (less indirect).

It kinda makes sense switching to Elm since it's an Elm project but I personally dislike Elm for doing anything other than websites 😅. I also enjoy writing Haskell.

I'll take a look at removing Stack.

**Comment by miniBill** [comment]
*poke*

**Comment by rl-king** [comment]
> _poke_

I've pushed an update that refactors the Haskell part to use just Cabal, is that easier to get nix working?

**Pull request closed without merging**
